name: Deploy Go Function (Reusable)

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      gcp_region:
        required: true
        type: string

    secrets:
      GCP_PROJECT_ID:
        required: true
      GCP_PROJECT_NUMBER:
        required: true
      GCP_SA_EMAIL:
        required: true
      GCP_WIF_PROVIDER:
        required: true
      GCP_BUCKET_NAME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    env:
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_project_number: ${{ secrets.GCP_PROJECT_NUMBER }}
      TF_VAR_service_account: ${{ secrets.GCP_SA_EMAIL }}
      TF_VAR_region: ${{ inputs.gcp_region }}
      TF_VAR_bucket_name: ${{ secrets.GCP_BUCKET_NAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - uses: hashicorp/setup-terraform@v3

      - name: Create Source Zip
        run: |
          cd function
          zip -r ../source.zip .

      - run: terraform init
      - run: terraform plan -input=false
      - run: terraform apply -auto-approve -input=false

