name: Monorepo Deploy

on:
  push:
    branches: [ main ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.filter.outputs.server }}
      notify: ${{ steps.filter.outputs.notify }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            server:
              - 'dogzh-server/**'
            notify:
              - 'notify-function/**'

  deploy-server:
    needs: changes
    if: needs.changes.outputs.server == 'true'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-function.yml
    with:
      working-directory: dogzh-server
      gcp_region: "us-central1"
      deploy-type: "run"
    secrets: inherit