name: Reusable Server Deploy

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
    secrets:
      GCP_PROJECT_ID: { required: true }
      GCP_WIF_PROVIDER: { required: true }
      GCP_SA_EMAIL: { required: true }
      GCP_SERVER_PORT: { required: true }

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Build and Push
        run: |
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev
          IMAGE_URL="${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dogzh-repo/server:${{ github.sha }}"
          docker build -t $IMAGE_URL .
          docker push $IMAGE_URL
          echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV
        working-directory: ${{ inputs.working-directory }}

      - name: Terraform
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="container_image=${{ env.IMAGE_URL }}" \
            -var="region=${{ vars.GCP_REGION }}" \
            -var="port=${{ secrets.GCP_SERVER_PORT }}"
        working-directory: ${{ inputs.working-directory }}