name: Reusable Server Deploy

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
    secrets:
      GCP_PROJECT_ID: { required: true }
      GCP_WIF_PROVIDER: { required: true }
      GCP_SA_EMAIL: { required: true }
      GCP_SERVER_PORT: { required: true }
      GCP_REGION: { required: true }

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Build and Push
        run: |
          REGION="${{ vars.GCP_REGION }}"
          REPO_DOMAIN="${REGION}-docker.pkg.dev"

          gcloud auth configure-docker $REPO_DOMAIN

          IMAGE_URL="$REPO_DOMAIN/${{ secrets.GCP_PROJECT_ID }}/dogzh-repo/server:${{ github.sha }}"

          docker build -t $IMAGE_URL .
          docker push $IMAGE_URL
          echo "$IMAGE_URL" > /tmp/image_url.txt

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          # Read the image URL we just built
          IMAGE_URL=$(cat /tmp/image_url.txt)

          terraform apply -auto-approve \
          -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
          -var="container_image=$IMAGE_URL" \
          -var="port=${{ secrets.GCP_SERVER_PORT }}"
          -var="region=${{ vars.GCP_REGION }}"